'use strict'

import FormattedToCountryCodeError from '../errors/FormattedToCountryCode'
import { ICountryCodes } from '../types/interfaces';

class FormattedToCountryCode {
    private _country: ICountryCodes;

    constructor (country: string) {
        this._country = this.init(country)
    }

    private init (value: string): ICountryCodes {
        try {
            const acronym: ICountryCodes[] = [
                { code: "BR", list: [ "brazil", "brasil"] },
                { code: "AF", list: [ "afghanistan", "afeganistão" ] },
                { code: "AX", list: [ "aland islands",  "ilhas aland" ] },
                { code: "AL", list: [ "albania", "albânia" ] },
                { code: "DZ", list: [ "algeria", "argélia" ] },
                { code: "AS", list: [ "american samoa", "samoa americana" ] },
                { code: "AD", list: [ "andorra" ] },
                { code: "AO", list: [ "angola" ] },
                { code: "AI", list: [ "anguilla" ] },
                { code: "AQ", list: [ "antarctica", "antártida" ] },
                { code: "AG", list: [ "antigua and barbuda", "antigua e barbuda" ] },
                { code: "AR", list: [ "argentina" ] },
                { code: "AM", list: [ "armenia", "armênia" ] },
                { code: "AW", list: [ "aruba" ] },
                { code: "AU", list: [ "australia", "austrália" ] },
                { code: "AT", list: [ "austria", "áustria" ] },
                { code: "AZ", list: [ "azerbaijan", "azerbaijão" ] },
                { code: "BS", list: [ "bahamas" ] },
                { code: "BH", list: [ "bahrain", "bahrein" ] },
                { code: "BD", list: [ "bangladesh" ] },
                { code: "BB", list: [ "barbados" ] },
                { code: "BY", list: [ "belarus" ] },
                { code: "BE", list: [ "belgium", "bélgica" ] },
                { code: "BZ", list: [ "belize" ] },
                { code: "BJ", list: [ "benin", "benim" ] },
                { code: "BM", list: [ "bermuda", "bermudas" ] },
                { code: "BT", list: [ "bhutan", "butão" ] },
                { code: "BO", list: [ "bolivia", "bolívia" ] },
                { code: "BA", list: [ "bosnia and herzegovina", "bósnia e herzegóvina" ] },
                { code: "BW", list: [ "botswana", "botsuana" ] },
                { code: "BV", list: [ "bouvet island", "ilha bouvet" ] },
                { code: "VG", list: [ "virgin islands (british)", "ilhas virgens britânicas" ] },
                { code: "IO", list: [ "british indian ocean territory", "território britânico do oceano índico" ] },
                { code: "BN", list: [ "brunei darussalam", "brunei" ] },
                { code: "BG", list: [ "bulgaria", "bulgária" ] },
                { code: "BF", list: [ "burkina faso" ] },
                { code: "BI", list: [ "burundi" ] },
                { code: "KH", list: [ "cambodia", "camboja" ] },
                { code: "CM", list: [ "cameroon", "camarões" ] },
                { code: "CA", list: [ "canada", "canadá" ] },
                { code: "CV", list: [ "cape verde", "cabo verde" ] },
                { code: "KY", list: [ "cayman islands", "ilhas cayman" ] },
                { code: "CF", list: [ "central african republic", "república centro-africana" ] },
                { code: "TD", list: [ "chad", "chade" ] },
                { code: "CL", list: [ "chile", "chile" ] },
                { code: "CN", list: [ "china", "china" ] },
                { code: "HK", list: [ "hong kong", "hong kong"] },
                { code: "MO", list: [ "macao", "macau" ] },
                { code: "CX", list: [ "chrstmas islands", "ilhas christmas" ] },
                { code: "CC", list: [ "cocos islands", "ilhas cocos" ] },
                { code: "CO", list: [ "colombia", "colômbia" ] },
                { code: "KM", list: [ "comoros", "comores" ] },
                { code: "CG", list: [ "republic of the congo", "república do congo" ] },
                { code: "CD", list: [ "republic democratic of the congo", "república democrática do congo" ] },
                { code: "CK", list: [ "cook islands", "ilhas cook" ] },
                { code: "CR", list: [ "costa rica", "costa rica" ] },
                { code: "CI", list: [ "cote d'ivoire", "costa do marfim" ] },
                { code: "HR", list: [ "croatia", "croácia" ] },
                { code: "CU", list: [ "cuba", "cuba" ] },
                { code: "BI", list: [ "burundi" ] },
                { code: "KH", list: [ "cambodia", "camboja" ] },
                { code: "CM", list: [ "cameroon", "camarões" ] },
                { code: "CY", list: [ "cyprus", "chipre" ] },
                { code: "CZ", list: [ "czech republic", "república checa" ] },
                { code: "DK", list: [ "denmark", "dinamarca" ] },
                { code: "DJ", list: [ "djibouti", "djibouti" ] },
                { code: "DM", list: [ "dominica", "dominica" ] },
                { code: "DO", list: [ "dominican republic", "república dominicana" ] },
                { code: "EC", list: [ "ecuador", "equador" ] },
                { code: "EG", list: [ "egypt", "egito"] },
                { code: "SV", list: [ "el salvador", "el salvador" ] },
                { code: "GQ", list: [ "equatorial guinea", "guiné equatorial" ] },
                { code: "ER", list: [ "erithea", "eritreia" ] },
                { code: "EE", list: [ "estonia", "estônia" ] },
                { code: "ET", list: [ "ethiopia", "etiópia" ] },
                { code: "FK", list: [ "falklands islands", "ilhas falklands" ] },
                { code: "FO", list: [ "faroe islands", "ilhas faroe" ] },
                { code: "FJ", list: [ "fiji", "fiji" ] },
                { code: "FI", list: [ "finland", "finlândia" ] },
                { code: "FR", list: [ "france", "frança" ] },
                { code: "GF", list: [ "french guiana", "guiana francesa" ] },
                { code: "PF", list: [ "french polynesia", "polinésia francesa" ] },
                { code: "TF", list: [ "french southern territories", "territórios franceses do sul" ] },
                { code: "GA", list: [ "gabon", "gabão" ] },
                { code: "GM", list: [ "gambia", "gâmbia" ] },
                { code: "GE", list: [ "georgia", "geórgia" ] },
                { code: "DE", list: [ "germany", "alemanha" ] },
                { code: "GH", list: [ "ghana", "gana" ] },
                { code: "GI", list: [ "gibraltar", "gibraltar" ] },
                { code: "GR", list: [ "greece", "grécia" ] },
                { code: "GL", list: [ "greenland", "groenlândia" ] },
                { code: "GD", list: [ "grenada", "granada" ] },
                { code: "GP", list: [ "guadeloupe", "guadalope"] },
                { code: "GU", list: [ "guam", "guam" ] },
                { code: "GT", list: [ "guatemala", "guatemala" ] },
                { code: "GG", list: [ "guernsey", "guernsey" ] },
                { code: "GN", list: [ "guinea", "guiné" ] },
                { code: "GW", list: [ "guinea-bissau", "guiné-bissau" ] },
                { code: "GY", list: [ "guyana", "guiana" ] },
                { code: "HT", list: [ "haiti", "haiti" ] },
                { code: "HM", list: [ "heard and mcdonald islands", "ilhas heard e mcdonald" ] },
                { code: "VA", list: [ "vatican city state", "cidade do vaticano" ] },
                { code: "HN", list: [ "honduras", "honduras" ] },
                { code: "HU", list: [ "hungary", "hungria" ] },
                { code: "IS", list: [ "iceland", "islândia" ] },
                { code: "IN", list: [ "india", "índia" ] },
                { code: "ID", list: [ "indonesia", "indonésia" ] },
                { code: "IR", list: [ "iran", "irã" ] },
                { code: "IQ", list: [ "iraq", "iraque" ] },
                { code: "IE", list: [ "ireland", "irlanda" ] },
                { code: "IM", list: [ "isle of man", "ilha de man" ] },
                { code: "IL", list: [ "israel", "israel" ] },
                { code: "IT", list: [ "italy", "itália" ] },
                { code: "JM", list: [ "jamaica", "jamaica" ] },
                { code: "JP", list: [ "japan", "japão" ] },
                { code: "JE", list: [ "jersey", "jersey"] },
                { code: "JO", list: [ "jordan", "jordânia" ] },
                { code: "KZ", list: [ "kazakhstan", "cazaquistão" ] },
                { code: "KE", list: [ "kenya", "quênia" ] },
                { code: "KI", list: [ "kiribati", "kiribati" ] },
                { code: "KP", list: [ "people's republic of korea", "república popular da coréia", "north korea", "coréia do norte" ] },
                { code: "KR", list: [ "republic of korea", "república da coréia", "south korea", "coréia do sul" ] },
                { code: "KW", list: [ "kwait", "kuwait" ] },
                { code: "KG", list: [ "Kyrgyzstan", "quirguistão" ] },
                { code: "LA", list: [ "lao", "lao" ] },
                { code: "LV", list: [ "latvia", "letônia" ] },
                { code: "LB", list: [ "lebanon", "líbano" ] },
                { code: "LS", list: [ "lesotho", "lesoto" ] },
                { code: "LR", list: [ "liberia", "libéria" ] },
                { code: "LY", list: [ "lybia", "líbia" ] },
                { code: "LI", list: [ "liechtenstein", "liechtenstein" ] },
                { code: "LT", list: [ "lithuania", "lituânia" ] },
                { code: "LU", list: [ "luxembourg", "luxemburgo" ] },
                { code: "MK", list: [ "macedonia", "macedônia" ] },
                { code: "MG", list: [ "madagascar", "madagascar" ] },
                { code: "MW", list: [ "malawi", "malauí" ] },
                { code: "MY", list: [ "malaysia", "malásia" ] },
                { code: "MV", list: [ "maldives", "maldivas" ] },
                { code: "ML", list: [ "mali", "mali"] },
                { code: "MT", list: [ "malta", "malta" ] },
                { code: "MH", list: [ "marshall islands", "ilhas marshall" ] },
                { code: "MQ", list: [ "martinique", "martinica" ] },
                { code: "MR", list: [ "mauritania", "mauritânia" ] },
                { code: "MU", list: [ "mauritius", "ilhas maurício" ] },
                { code: "YT", list: [ "mayotte", "mayotte"] },
                { code: "MX", list: [ "mexico", "méxico" ] },
                { code: "FM", list: [ "micronesia", "micronésia" ] },
                { code: "MD", list: [ "moldova", "moldávia" ] },
                { code: "MC", list: [ "monaco", "mônaco" ] },
                { code: "MN", list: [ "mongolia", "mongólia" ] },
                { code: "ME", list: [ "montenegro", "montenegro" ] },
                { code: "MS", list: [ "montserrat", "montserrat" ] },
                { code: "MA", list: [ "morocco", "marrocos" ] },
                { code: "MZ", list: [ "mozambique", "moçambique" ] },
                { code: "MM", list: [ "myanmar", "myanmar" ] },
                { code: "NA", list: [ "namibia", "namíbia" ] },
                { code: "NR", list: [ "nauru", "nauru" ] },
                { code: "NP", list: [ "nepal", "nepal" ] },
                { code: "NL", list: [ "netherlands", "holanda" ] },
                { code: "CW", list: [ "curaçao", "curaçao" ] },
                { code: "NC", list: [ "new caledonia", "nova caledônia" ] },
                { code: "NZ", list: [ "new zealand", "nova zelândia"] },
                { code: "NI", list: [ "nicaragua", "nicarágua" ] },
                { code: "NE", list: [ "niger", "níger" ] },
                { code: "NG", list: [ "nigeria", "nigéria" ] },
                { code: "NU", list: [ "niue", "niue" ] },
                { code: "NF", list: [ "norfolk islands", "ilhas norfolk" ] },
                { code: "MP", list: [ "northern mariana islands", "ilhas marianas do norte"] },
                { code: "NO", list: [ "norway", "noruega" ] },
                { code: "OM", list: [ "oman", "omã" ] },
                { code: "PK", list: [ "pakistan", "paquistão" ] },
                { code: "PW", list: [ "palau", "palau" ] },
                { code: "PS", list: [ "palestina", "palestina" ] },
                { code: "PA", list: [ "papua new guinea", "papua nova guiné" ] },
                { code: "PG", list: [ "paraguay", "paraguai" ] },
                { code: "PY", list: [ "peru", "peru" ] },
                { code: "PE", list: [ "philippines", "filipinas" ] },
                { code: "PH", list: [ "pitcairn", "ilhas pitcairn" ] },
                { code: "PN", list: [ "poland", "polônia" ] },
                { code: "PT", list: [ "portugal", "portugal" ] },
                { code: "PR", list: [ "puerto rico", "porto rico" ] },
                { code: "QA", list: [ "qatar", "qatar" ] },
                { code: "RE", list: [ "reunion", "reunião" ] },
                { code: "RO", list: [ "romania", "romênia" ] },
                { code: "RU", list: [ "russia", "rússia"] },
                { code: "RW", list: [ "rwanda", "ruanda" ] },
                { code: "BL", list: [ "saint-barthelemy", "são bartolomeu" ] },
                { code: "SH", list: [ "saint helena", "santa helena" ] },
                { code: "KH", list: [ "saint kitts and nevis", "saint kitts and nevis" ] },
                { code: "LC", list: [ "saint lucia", "saint lucia" ] },
                { code: "MF", list: [ "saint-martin", "são martinho"] },
                { code: "PM", list: [ "saint pierre and miquelon", "saint pierre e miquelon" ] },
                { code: "VC", list: [ "saint vincent and grenadines", "são vicente e grenadinas" ] },
                { code: "WS", list: [ "samoa", "samoa" ] },
                { code: "SM", list: [ "san marino", "san marino" ] },
                { code: "ST", list: [ "sao tome and principe", "são tomé e príncipe" ] },
                { code: "SA", list: [ "saudi arabia", "arábia saudita" ] },
                { code: "SN", list: [ "senegal", "senegal" ] },
                { code: "RS", list: [ "serbia", "sérvia" ] },
                { code: "SC", list: [ "seychelles", "seychelles" ] },
                { code: "SL", list: [ "sierra leone", "serra leoa" ] },
                { code: "SG", list: [ "singapure", "cingapura" ] },
                { code: "SK", list: [ "slovakia", "eslováquia" ] },
                { code: "SI", list: [ "slovenia", "eslovênia" ] },
                { code: "SB", list: [ "solomon islands", "ilhas salomão" ] },
                { code: "SO", list: [ "somalia", "somália" ] },
                { code: "ZA", list: [ "south africa", "áfrica do sul" ] },
                { code: "GS", list: [ "south georgia and the south sandwich islands", "ilhas geórgia do sul e sandwich do sul"] },
                { code: "SS", list: [ "south sudan", "sudão do sul" ] },
                { code: "ES", list: [ "spain", "espanha" ] },
                { code: "LK", list: [ "sri lanka", "sri lanka" ] },
                { code: "SD", list: [ "sudan", "sudão" ] },
                { code: "SR", list: [ "suriname", "suriname" ] },
                { code: "SJ", list: [ "svalbard and jan mayen islands", "ilhas svalbard e jan mayen"] },
                { code: "SZ", list: [ "swaziland", "suazilândia" ] },
                { code: "SE", list: [ "sweden", "suécia" ] },
                { code: "CH", list: [ "switzerland", "suiça" ] },
                { code: "SY", list: [ "syria", "síria" ] },
                { code: "TW", list: [ "taiwan", "taiwan" ] },
                { code: "TJ", list: [ "tajikistan", "tajiquistão" ] },
                { code: "TZ", list: [ "tanzania", "tanzânia" ] },
                { code: "TH", list: [ "thailand", "tailândia" ] },
                { code: "TL", list: [ "timor-leste", "timor leste" ] },
                { code: "TG", list: [ "togo", "togo" ] },
                { code: "TK", list: [ "tokelau", "tokelau" ] },
                { code: "TO", list: [ "tonga", "tonga" ] },
                { code: "TT", list: [ "trinidad and tobago", "trinidad and tobago" ] },
                { code: "TN", list: [ "tunisia", "tunísia" ] },
                { code: "TR", list: [ "turkey", "turquia" ] },
                { code: "TM", list: [ "turkmenistan", "turcomenistão" ] },
                { code: "TC", list: [ "turks and caicos islands", "ilhas turks e caicos"] },
                { code: "TV", list: [ "tuvalu", "tuvalu" ] },
                { code: "UG", list: [ "uganda", "uganda" ] },
                { code: "UA", list: [ "ukraine", "ucrânia" ] },
                { code: "AE", list: [ "united arab emirates", "emirados árabes unidos" ] },
                { code: "UK", list: [ "united kingdom", "reino unido" ] },
                { code: "US", list: [ "united states", "estados unidos"] },
                { code: "UM", list: [ "united states mynor outlying islands", "ilhas menores distantes dos estados unidos" ] },
                { code: "UY", list: [ "uruguay", "uruguai" ] },
                { code: "UZ", list: [ "uzbekistan", "usbequistão" ] },
                { code: "VU", list: [ "vanuatu", "vanuatu" ] },
                { code: "VE", list: [ "venezuela", "venezuela" ] },
                { code: "VN", list: [ "vietnam", "vietnã" ] },
                { code: "VI", list: [ "us virgin islands", "ilhas virgens americanas" ] },
                { code: "WF", list: [ "wallis and futuna islands", "wallis e futuna" ] },
                { code: "EH", list: [ "western sahara", "saara ocidental" ] },
                { code: "YE", list: [ "yemen", "iêmen" ] },
                { code: "ZM", list: [ "zambia", "zâmbia" ] },
                { code: "ZW", list: [ "zimbabwe", "zimbábue" ] },
            ]

            const term:ICountryCodes[] = acronym.filter(c => c.list.indexOf(value.toLowerCase()) !== -1)
            if (term.length === 0)
                throw new FormattedToCountryCodeError(404, 'Não foi possível vincular o país informado à lista de ISO Codes')

            return term[0]

        } catch (err: unknown) {
            throw new FormattedToCountryCodeError(400, `Erro ao configurar o código de país: ${ err }`);
        }
    }

    public formatCountry () : ICountryCodes {
        return this._country
    }

}

export default FormattedToCountryCode